#!/bin/sh

# Mount devpts
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t tmpfs -o size=100M tmp /tmp

#socat VSOCK-LISTEN:6294,reuseaddr,fork EXEC:'/bin/bash -li',pty,stderr,setsid,sigint,sane,ctty

# Start remote shell
/opt/machina/vsock-shell &

# Setup networking
/opt/machina/gvforwarder-proxy


